### ISSUE TITLE
想进行类似J2V8的绑定

### ISSUE THREAD

**Issue by pboymt** [cstsinghua/V8Android#2]
新人刚接触在Android上用v8，请问如何像J2V8这个项目一样绑定v8引擎到Java呢？

**Comment by cstsinghua** [comment]
其实可以用新版的v8构建出来的静态库，连接成动态库，然后替换掉J2V8的NodeJS so库，保持J2V8的jar(java代码)和JNI 粘合层(cpp代码)，生成新的库。这样既保留了J2V8的接口，而实际上底层又是用的新版的v8构建出来的库

**Comment by pboymt** [comment]
J2V8的V8版本都老掉牙了，连Promise都不支持……

**Comment by cstsinghua** [comment]
就是替换掉底层的v8就可以，保留J2V8的java侧代码和JNI层的粘合代码，这样保留了接口一致性，也支持JS的新特性。目前有朋友采用构建的6.5的v8移植到J2V8里面成功了

**Comment by zhangjun725** [comment]
@pboymt 有办法支持Promise  await /async了吗？
